name: estudos_ml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - asttokens==3.0.1
      - beautifulsoup4==4.14.3
      - certifi==2026.1.4
      - decorator==5.2.1
      - executing==2.2.1
      - idna==3.11
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.16
      - matplotlib-inline==0.2.1
      - numpy==2.2.6
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - scipy==1.15.3
      - six==1.17.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - urllib3==2.6.3
      - wcwidth==0.3.0
      - webencodings==0.5.1
      - widgetsnbextension==4.0.15
prefix: /home/thiago/miniconda3/envs/estudos_ml
